development:
  adapter: postgresql
  encoding: unicode
  database: ucdnewsapp_development
  pool: 5
  username: huyipeng
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ucdnewsapp_test
  pool: 5
  username: huyipeng
  password: